require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec_rails
  - rubocop-slim

AllCops:
  NewCops: enable

# Disable checking for use of click_button
Capybara/ClickLinkOrButtonStyle:
  Enabled: false
