default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "your_username" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "your_password" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: study_fun_development

test:
  <<: *default
  database: study_fun_test

production:
  <<: *default
  database: study_fun_production
  username: study_fun
  password: <%= ENV["STUDY_FUN_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "production_host" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
